branches:
  only:
    - master

image: Visual Studio 2019

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org  

init:
  - SET PATH=%GOPATH%\bin;%PATH%
  - git config --global core.autocrlf input
  - chcp 1252

install:
  - go version
  - go env
  - go install github.com/tischda/go2xunit@latest

build_script:
  - go build -ldflags "all=-s -w"

test_script:
  - go test -v -cover
  - go test -v | go2xunit.exe -xunitnet > xunit-report.xml

artifacts:
  - path: gcd.exe
    name: gcd

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
    