branches:
  only:
    - master

image: Visual Studio 2019

environment:
  GOPATH: c:\gopath

init:
  - SET PATH=%GOPATH%\bin;%PATH%
  - git config --global core.autocrlf input

install:
  - go version
  - go env
  - mkdir %GOPATH%
  # This is not a dependency but a test report filter...
  # WARNING: behaviour will change in go 1.16
  # cf. https://stackoverflow.com/questions/24878737/what-is-the-difference-between-go-get-and-go-install
  - set GO111MODULE=off
  - go get github.com/tischda/go2xunit
  - set GO111MODULE=on

build_script:
  - go build

test_script:
  - go test -v -cover
  - go test -v | go2xunit.exe -xunitnet > xunit-report.xml
  - gcd.exe data

artifacts:
  - path: gcd.exe
    name: gcd

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
    